// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt (args[0]);
		int countMore = 0, countLess = 0;
		for (int i=0; i<N; i++)
		{
			if (Math.random() > 0.5) {
				countMore++;
			} else {
				countLess++;
			}
		}
		System.out.println("> 0.5: " + countMore + " times");
		System.out.println("<= 0.5: " + countLess + " times");
		if (countLess != 0) {
			System.out.println("Ratio: " + (double) countMore / countLess);
		}
	}
}
